apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crypto-node-pv-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0856191a55a37c655
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-node-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-node-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: crypto-node
    spec:
      containers:
      - name: crypto-node-container
        image: angpenghian/crypto_chain-main_1.2.1:latest
        ports:
        - name: cosmos-rpc
          containerPort: 1317
        - name: tendermint-rpc
          containerPort: 26657
        volumeMounts:
        - name: crypto-data
          mountPath: /efs-data
      volumes:
      - name: crypto-data
        persistentVolumeClaim:
          claimName: crypto-node-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-node-service
  namespace: default
spec:
  selector:
    app: crypto-node
  type: LoadBalancer
  ports:
    - name: cosmos-rpc
      port: 1317
      targetPort: 1317
    - name: tendermint-rpc
      port: 26657
      targetPort: 26657